# -*- coding: utf-8 -*-
"""Major animal repellent system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1awSJMb_c2cQJep4dXndabW_frb6a6_pS

# **Importing our Modules**
"""

from keras.preprocessing import image
from keras.applications.vgg19 import preprocess_input,decode_predictions
import numpy as np

import keras.utils as image

from keras.applications.vgg19 import VGG19
model = VGG19(weights='imagenet')

def preprocess_data(x):
  x = np.expand_dims(x, axis=0)
  x = preprocess_input(x)
  return x

# xx=preprocess_data(x)

"""# **Accessing Drive**"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Predicting Invaders**"""

from IPython.utils.text import string
import cv2
def FrameCapture(path):
    vidObj = cv2.VideoCapture(path)
    count = 0
    success = 1
    f = open("otuput.txt", "w+")
    frames = vidObj.get(cv2.CAP_PROP_FRAME_COUNT)
    fps = vidObj.get(cv2.CAP_PROP_FPS)
    while success:
        success, image = vidObj.read()
        img=cv2.resize(image, (224,224))
        xx=preprocess_data(img)
        preds = model.predict(xx)
        f.write(str(decode_predictions(preds, top=1)[0][0][1]))
        f.write("\n")
        print('Predicted:', decode_predictions(preds, top=1)[0][0][1],end="\n")
        count = count + 1
        if(count == 10):
          break
    f.close()
FrameCapture('/content/drive/MyDrive/video_20230423_232648_edit.mp4')

#!pip install vonage

"""# **Inspecting the invade using count function**"""

f = open("/content/otuput.txt",'r')
a = f.readlines()
u  = []
m  = 0
p = ""
for i in a:
  if i in u:
    continue
  else:
    u.append(i)
for i in u:
  c = a.count(i)
  if(c>m):
    m = c
    p = i
print(p)

"""# **Time showing Module**"""

from pytz import timezone
from datetime import datetime

time_now = datetime.now(timezone("Asia/Kolkata"))
current_time = time_now.strftime("%H:%M:%S")

print("The current date and time is", current_time)

"""# **Intimating user about the invader**"""

import http.client
#api url
conn = http.client.HTTPSConnection("inteltech.p.rapidapi.com")
#payload for SMS API
payload = "sms=%2B917285906696&message=Dear%20User%20your%20Field%20is%20Invaded%20By%20"+p+" At "+current_time+".&key=5326B3A5-A56E-929C-D0F0-F89C87718ABA&username=n170053%40rguktn.ac.in"

#API HEADERS
headers = {
    'content-type': "application/x-www-form-urlencoded",
    'X-RapidAPI-Key': "af3daed231msh45f1b80194e4446p17dc79jsn0b54321eb7e1",
    'X-RapidAPI-Host': "inteltech.p.rapidapi.com"
}

#sending Request with api
conn.request("POST", "/send.php", payload, headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

#%2B919703229944%2C  %2B916302384112%2C  %2B916305856390%2C  %2B917285906696%2C  %2B917680817406%2C  %2B919885412137%2C  %2B917680817406%2C
# import vonage
# client = vonage.Client(key="617a8790", secret="hWBrtNv7arCp6DXS")
# sms = vonage.Sms(client)
# responseData = sms.send_message(
#     {
#         "from": "Vonage APIs",
#         "to": "919515037553",
#         "text": 'hola',
#     }
# )

# if responseData["messages"][0]["status"] == "0":
#     print("Message sent successfully.")
# else:
#     print(f"Message failed with error: {responseData['messages'][0]['error-text']}")